name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Publish Project
        run: dotnet publish $(find . -name "*.csproj" | head -n 1) -c Release -o release

      - name: Fix and Deploy
        run: |
          # Procura onde o index.html foi parar
          INDEX_PATH=$(find release -name "index.html" | head -n 1)
          
          if [ -z "$INDEX_PATH" ]; then
            echo "ERRO: index.html não encontrado! Verifique se o projeto é Blazor WebAssembly."
            exit 1
          fi
          
          # Pega a pasta onde o index.html está
          PUBLISH_DIR=$(dirname "$INDEX_PATH")
          
          # Ajusta o base href
          sed -i 's/<base href="\/" \/>/<base href="\/Blazor-AppWeb\/" \/>/g' "$INDEX_PATH"
          
          # Cria arquivos necessários para o GitHub
          touch "$PUBLISH_DIR/.nojekyll"
          cp "$INDEX_PATH" "$PUBLISH_DIR/404.html"
          
          # Salva o caminho da pasta para o próximo passo
          echo "DEPLOY_PATH=$PUBLISH_DIR" >> $GITHUB_ENV

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.DEPLOY_PATH }}
          branch: gh-pages