name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Publish Project
        run: dotnet publish $(find . -name "*.csproj" | head -n 1) -c Release -o release

      - name: Fix Structure for GitHub Pages
        run: |
          # Se o .NET 10 criou uma subpasta wwwroot dentro de release, movemos tudo para a raiz de release
          if [ -d "release/wwwroot" ]; then
            cp -r release/wwwroot/* release/
          fi
          # Cria o arquivo .nojekyll dentro da pasta que ser√° enviada
          touch release/.nojekyll

      - name: Change base-tag in index.html
        run: |
          INDEX_FILE=$(find release -name "index.html" | head -n 1)
          if [ -f "$INDEX_FILE" ]; then
            sed -i 's/<base href="\/" \/>/<base href="\/Blazor-AppWeb\/" \/>/g' "$INDEX_FILE"
          fi

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release  # Enviamos a pasta release inteira
          branch: gh-pages