name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Publish Project
        run: dotnet publish $(find . -name "*.csproj" | head -n 1) -c Release -o release

      - name: Organize Files for GitHub Pages
        run: |
          # 1. Entra na pasta de saída e move tudo para a raiz do deploy
          cd release/wwwroot
          # 2. Cria o arquivo .nojekyll aqui dentro
          touch .nojekyll
          # 3. Ajusta o base href no index.html (Vital para não dar tela branca)
          sed -i 's/<base href="\/" \/>/<base href="\/Blazor-AppWeb\/" \/>/g' index.html
          # 4. Se houver um 404.html, fazemos o mesmo
          cp index.html 404.html

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot # Agora enviamos exatamente a pasta que contém o index.html
          branch: gh-pages